# Generated by Django 5.1.6 on 2025-09-28 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0003_remove_task_assignee_remove_task_reviewer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assignees',
            new_name='assignee',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='reviewers',
            new_name='reviewer',
        ),
    ]
