# Generated by Django 5.1.6 on 2026-01-17 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['title']},
        ),
    ]
